### ISSUE TITLE
Allow partial tracing with simulation

### ISSUE THREAD

**Issue by enjoy-digital** [enjoy-digital/linux-on-litex-vexriscv#17]
To ease debug, allow enabling tracing after a number of cycles.

**Comment by enjoy-digital** [comment]
Added with https://github.com/enjoy-digital/litex/commit/4b6ad8aa0dc9fbd910695769cc178edef3af712e and https://github.com/enjoy-digital/linux-on-litex-vexriscv/commit/359c2889a7c59d28598d73d1b0508a4c229efadc

@Dolu1990: you can now do: ./sim.py --trace --trace-start=10000 --trace-end=20000 to start tracing at cycle 10000 and end at cycle 20000. If you don't specify --trace-start, default value is 0. If you don't specify --trace-end, default value is infinite.

**Comment by Dolu1990** [comment]
Great, thanks :D
